### ISSUE TITLE
64 bit bug. It thinks distant past is in future.

### ISSUE THREAD

**Issue by malhal** [nikilster/NSDate-Time-Ago#10]
Calling `[[NSDate distantPast] formattedAsTimeAgo]` gives "In The Future".

The bug is in this line:

 `NSTimeInterval secondsSince = -(int)[self timeIntervalSinceDate:now];`

It should be 

`NSTimeInterval secondsSince = -(NSInteger)[self timeIntervalSinceDate:now];`

**Comment by nikilster** [comment]
@malhal great thanks - will merge this!
